### PR TITLE
[WIP] Cleanup

### LINKED ISSUE #7: Consistent use of Base.@kwdef
In the definitions.jl file it seems that some of the structs make use of Base.@kwdef and some others do not. Could you  double check that this is intended? It would be nice to have all table types following the same construction pattern.

### PR DESCRIPTION
**Pull request by juliohm**
Hi @rmcaixeta, I've started to clean up the package for heavy use with students next quarter. Would you have some time tomorrow or over the weekend to clarify what some of the functions are doing? The plan is to improve readability before fixing bugs.

- [x] desurvey
- [ ] composite
- [ ] tests
- [x] docs

Fixes #7

### CODE REVIEW

**Comment by rmcaixeta** [comment]
That's great, thanks Julio
Point me the confusing parts, please, I'll send you an audio or a text explaining them.

Just taking a quick look here. Please, don't delete the validations part. I don't mind if you prefer it outside `drillholes` call as an extra function, but it's really important to have that. Database errors are really really common and sometimes it' not easy to find/correct them.

**Comment by juliohm** [comment]
Awesome, thanks! I am deleting the validations in order to reintroduce them
later with code that is more readable.
The API will improve considerably so the validation code will need to be
adapted accordingly. Hopefully we will
have an option to load the data with cylinder geometries from Meshes.jl as
an option.

I will share more updates here by the end of the day. Thanks for helping
with the process. :)

Em sex., 18 de jun. de 2021 às 08:15, Rafael Caixeta <
***@***.***> escreveu:

**Comment by juliohm** [comment]
Hi @rmcaixeta , I'm almost done with the desurveying step 🎉 In order to finish it, I need to understand what the `mergetables` function is doing exactly. I know it is merging the interval tables but I thought that we could just use a simple join from DataFrames.jl? Could you please elaborate on the expected result? If you can describe it with a simple sentence, I can work on my own tomorrow to reproduce the results.

**Comment by rmcaixeta** [comment]
Great! The point to consider is that one table interval can overlap the other, that's why I made an additional step before the join. Maybe it's possible to adapt to a simple join, but I'm not sure. Example: merging one litho interval FROM 0 TO 10 with an assay interval FROM 5 TO 6. The output drillhole table will have 3 intervals: 0-5, 5-6 and 6-10. All with same litho value, but only 5-6 will have assay value, the others will have missing assay.

**Comment by juliohm** [comment]
Awesome the example helped a lot understand the challenge. Tomorrow I'll
try to work on this.

**Comment by juliohm** [comment]
Hi @rmcaixeta I have a few more questions before I can finish the desurveying step:

1. Is it correct to say that the Z coordinate in the collar file is always non-negative with the topography at Z = 0? I understand that we start at Z = 0 and increase towards the maximum depth, which is sometimes reported in the file.
2. When the input survey table has positive dip pointing downwards we don't need to flip its sign because it is already aligned with the collar convention, correct?
3. The two functions you wrote for the arc and tangent methods assume that the dip angles are positive pointing downwards, correct? So if the user specifies that the input survey has positive dip pointing upwards we need to flip the sign.

Assume that I have processed the trajectories (i.e. trace) and have found the sub-intervals with values as we discussed recently:

```julia
(4×7 DataFrame
 Row │ HOLEID  AT       AZM      DIP      X        Y        Z       
     │ Int64   Float64  Float64  Float64  Float64  Float64  Float64 
─────┼──────────────────────────────────────────────────────────────
   1 │      1      0.0      0.0     89.0  1.0      1.0      1.0
   2 │      1      5.0      1.0     88.0  1.00152  1.13087  5.99822
   3 │      2      0.0     20.0     77.0  2.0      2.0      2.0
   4 │      2      5.0     21.0     76.0  2.4091   3.09313  6.86179, 6×5 DataFrame
 Row │ HOLEID  FROM     TO       A        L      
     │ Int64   Float64  Float64  Int64?   String 
─────┼───────────────────────────────────────────
   1 │      1      0.0      1.0  missing  A
   2 │      1      1.0      3.5        1  A
   3 │      1      3.5      8.0        2  A
   4 │      2      0.0      4.4        3  B
   5 │      2      4.4      7.0        3  C
   6 │      2      7.0      8.0  missing  C)
```

In order to assign the X, Y, Z coordinates to the attribute table, I am planning to:

1. Create a new column AT with the middle of the FROM -- TO interval
2. Do an `outerjoin(trace, table, on [:HOLEID,:AT])` to get X, Y, Z when possible
3. Interpolate DIP and AZM for the AT values without X, Y, Z
4. Apply the arc or tangent method again to fill in the coordinates

Is that the standard approach? Please let me know if there is something out of place, I am planning to keep working on it today and next week.

**Comment by juliohm** [comment]
I think my assumption (1) above is incorrect. Do I understand correctly that the collar file could even be omitted and only be considered at the very end of the pipeline? It just shifts all xyz coordinates for each dill hole. If we assume that the top of the hole is at coordinates (0,0,0) we can do the calculations and at the very end add back the collar, correct? That would simplify the code even more.

**Comment by rmcaixeta** [comment]
Hey Julio. I think that for 2 and 3, it's the inverse of what you wrote. The functions were written for negative downwards. I'm not sure if I understood 1, but I'd say no, Z can be negative in some cases (e.g. underground mine). Your strategy 1-4 seems ok. About considering the collars coordinates only in the end, seems to be a possible approach, need to try it

**Comment by juliohm** [comment]
Thanks @rmcaixeta I will try to get it done today.

The pseudocode I have in mind looks like this:

1. join interval tables and fill sub-intervals when possible
2. assign new column AT as (FROM + TO) / 2
3. join with survey table on HOLEID and AT
4. intepolate AZM and DIP as a function of AT
5. join with collar table on AT and compute X, Y, Z

This should simplify the code greatly. Let me know if you spot any conceptual problem with the pseudocode. I will report the results by the end of the day.

**Comment by rmcaixeta** [comment]
Great! The pseudocode looks good.

Just one thing to have in mind about the survey interpolation, in case
you're thinking of not storing original survey data (currently
DrillHole.trace)
Some softwares store it, others not. I prefer storing it, here an example
of why not storing the originals can create bad results in some cases:
consider you have 10m-spaced litho intervals and 3m-spaced downhole
surveys. You can get the center coordinate of the intervals correctly in
the 1st desurvey. But if you composite those drillholes later into 1-m
samples, the coordinates of each 1-m interval will be biased if you use
only the interpolated survey at the 10m samples, instead the original 3m
survey data.

Em seg., 21 de jun. de 2021 às 07:52, Júlio Hoffimann <
***@***.***> escreveu:

**Comment by juliohm** [comment]
I think I finished the desurvey step 👍🏽 Appreciate if you can take a look at this example to see if the results make sense:

```julia
julia> collar = Collar(DataFrame(HOLEID=1:2, X=1:2, Y=1:2, Z=1:2))
Collar{DataFrame}(2×4 DataFrame
 Row │ HOLEID  X      Y      Z     
     │ Int64   Int64  Int64  Int64 
─────┼─────────────────────────────
   1 │      1      1      1      1
   2 │      2      2      2      2, :HOLEID, :X, :Y, :Z)

julia> survey = Survey(DataFrame(HOLEID=[1,1,2,2], AT=[0,5,0,5], AZM=[0,1,20,21], DIP=[89,88,77,76]))
Survey{DataFrame}(4×4 DataFrame
 Row │ HOLEID  AT     AZM    DIP   
     │ Int64   Int64  Int64  Int64 
─────┼─────────────────────────────
   1 │      1      0      0     89
   2 │      1      5      1     88
   3 │      2      0     20     77
   4 │      2      5     21     76, :HOLEID, :AT, :AZM, :DIP)

julia> assays = Interval(DataFrame(HOLEID=[1,1,2], FROM=[1,3.5,0], TO=[3.5,8,7], A=[1,2,3]))
Interval{DataFrame}(3×4 DataFrame
 Row │ HOLEID  FROM     TO       A     
     │ Int64   Float64  Float64  Int64 
─────┼─────────────────────────────────
   1 │      1      1.0      3.5      1
   2 │      1      3.5      8.0      2
   3 │      2      0.0      7.0      3, :HOLEID, :FROM, :TO)

julia> lithos = Interval(DataFrame(HOLEID=[1,2,2], FROM=[0,0,4.4], TO=[8,4.4,8], L=["A","B","C"]))
Interval{DataFrame}(3×4 DataFrame
 Row │ HOLEID  FROM     TO       L      
     │ Int64   Float64  Float64  String 
─────┼──────────────────────────────────
   1 │      1      0.0      8.0  A
   2 │      2      0.0      4.4  B
   3 │      2      4.4      8.0  C, :HOLEID, :FROM, :TO)

julia> dh = desurvey(survey, collar, [assays, lithos])
10×11 DataFrame
 Row │ A        L        HOLEID  FROM     TO       AT       AZM      DIP      X        Y        Z         
     │ Int64?   String?  Int64   Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64   
─────┼────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ missing  missing       1      0.0      0.0     0.0      0.0    -89.0   1.0      1.0       1.0
   2 │ missing  A             1      0.0      1.0     0.5      0.1    -88.9   1.00001  1.00916   0.500084
  ⋮  │    ⋮        ⋮       ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮         ⋮
   9 │       3  C             2      4.4      7.0     5.7     21.14   -75.86  2.47011  3.25201  -3.54079
  10 │ missing  C             2      7.0      8.0     7.5     21.5    -75.5   2.632    3.66674  -5.28486
                                                                                            6 rows omitted

julia> dh.X'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  1.00001  1.00021  1.00132  1.00183  2.0  2.17392  2.40893  2.47011  2.632

julia> dh.Y'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  1.00916  1.0481  1.13087  1.15802  2.0  2.4721  3.09321  3.25201  3.66674

julia> dh.Z'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  0.500084  -1.24948  -3.99822  -4.74773  2.0  -0.141693  -2.86179  -3.54079  -5.28486

julia> dh.AT'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 0.0  0.5  2.25  5.0  5.75  0.0  2.2  5.0  5.7  7.5

julia> dh.A'
1×10 adjoint(::Vector{Union{Missing, Int64}}) with eltype Union{Missing, Int64}:
 missing  missing  1  missing  2  missing  3  missing  3  missing

julia> dh.L
10-element Vector{Union{Missing, String}}:
 missing
 "A"
 "A"
 missing
 ⋮
 "B"
 missing
 "C"
 "C"
```

The final result will have the finest resolution of survey and intervals. I don't know if I followed the issue you raised in the last comment. Isn't this result table complete? We can composite it later and it will contain all possible depths from intervals and survey together.

**Comment by juliohm** [comment]
Hi @rmcaixeta I was able to load a massive dataset with more than 190k intervals with this PR in 20s. If the pseudocode I shared above is conceptually correct, I can move on to the composite step next week after I am done with some research presentations.

Please let me know if the issue you shared in the last comment is still valid with this implementation. I think the way I am organizing the output table contains all the information needed from all input tables, but I may be wrong.

**Comment by rmcaixeta** [comment]
Great, thanks @juliohm . It's not common to have zero length intervals in drillhole table, but this trick will probably avoid the issue I mentioned earlier (except when compositing an already composited interval). I'll write a simple test later to make it clear to you and guarantee it works well. 

I suggest you run the previous tests with this current approach. I'll try to check it in a little more detail until the weekend.

**Comment by juliohm** [comment]
Sounds good @rmcaixeta , one thing we can also do is save a new column that stores the source of the row from either survey or interval files. That way we can easily filter all rows of the table that correspond to the survey without assumptions about the interval lengths (FROM = TO).

I will try to reintroduce the previous tests with the new implementation to see if they pass. I remember seeing some different results and it would be nice to double check it.

**Comment by juliohm** [comment]
@rmcaixeta I've introduced the two previous tests and it would be nice if you could check the results. Given the amount of code change, I would just close this PR branch and test locally without trying to read the github diff.

After you give me the green light, I can start working on the composite functionality. If you have papers explaining the methods in detail, that would be great.

**Comment by rmcaixeta** [comment]
Thanks Julio. I'll take a look and run local tests later today. Abzalov book has one page quickly explaining these two methods (Chap 13)

**Comment by rmcaixeta** [comment]
Made a more detailed check here
The merged intervals are ok, I even found a small bug in the current version that is corrected in yours
But there is some problem in your interpolation algorithm to get X, Y, Z. And the benchmarking show some considerable differences in time and allocations. These will need some further investigation. I'll send you the reference data to check.
Another small thing I suggest to change: the order of arguments from `desurvey(survey, collar, intervals)` to `desurvey(collar, survey, intervals)`, which is more intuitive for regular users of other softwares.

Here the coordinate errors using Leapfrog as reference to check:

- Spherical arc
Current version X: mean absolute error = 0.00; max error = 0.02
Current version Y: mean absolute error = 0.00; max error = 0.05
Current version Z: mean absolute error = 0.00; max error = 0.01
After cleanup X: mean absolute error = 0.07; max error = 54.81
After cleanup Y: mean absolute error = 0.04; max error = 26.79
After cleanup Z: mean absolute error = 0.04; max error = 74.21

- Tangent:
Current version X: mean absolute error = 0.00; max error = 0.00
Current version Y: mean absolute error = 0.00; max error = 0.00
Current version Z: mean absolute error = 0.00; max error = 0.00
After cleanup X: mean absolute error = 0.24; max error = 56.98
After cleanup Y: mean absolute error = 0.91; max error = 38.91
After cleanup Z: mean absolute error = 0.40; max error = 78.91

And here the comparisons using BenchmarkTools:

- @btime, 4 threads
Current version: 3.087 s (28233648 allocations: 1.43 GiB)
After cleanup: 23.508 s (344471092 allocations: 44.02 GiB)

I'll send you the link of the files I used in Zulip in some minutes

**Comment by juliohm** [comment]
Awesome @rmcaixeta , thanks for the detailed checks. I will try to take a look at it today or tomorrow.

It is interesting how the X, Y, Z coordinates are so different in the two implementations. I didn't touch the step methods, just moved the calculation to the very end of the pipeline. Maybe the difference is explained by the fact that you were calculating the trace coordinates without considering the intervals? When we consider the intervals we have more steps and consequently will have different trajectories at the end. I wonder what is the best approach here. Do you think it is reasonable to consider all intervals first, and then interpolate the AZM and DIP linearly as I am doing?

>Another small thing I suggest to change: the order of arguments from desurvey(survey, collar, intervals) to desurvey(collar, survey, intervals), which is more intuitive for regular users of other softwares.

I will flip the order 👍🏽 I thought the collar file was "more secondary" than the survey file.

Regarding the performance, I think I know where exactly is the bottleneck. I will see if I can reduce the memory allocations and speedup the code in the process. I noticed that in the previous implementation you were computing various lengths for the intervals, maybe if you explain at a high-level what the algorithm was doing, I can try to reproduce it again. The current implementation does not compute lengths explicitly. I will check what is causing the slow down.

**Comment by rmcaixeta** [comment]
Great @juliohm 
Some comments below

> It is interesting how the X, Y, Z coordinates are so different in the two implementations. I didn't touch the step methods, just moved the calculation to the very end of the pipeline. Maybe the difference is explained by the fact that you were calculating the trace coordinates without considering the intervals? When we consider the intervals we have more steps and consequently will have different trajectories at the end. I wonder what is the best approach here. Do you think it is reasonable to consider all intervals first, and then interpolate the AZM and DIP linearly as I am doing?

Yeah, maybe interpolating the azm and dip caused that. I used the original azm and dip from survey file and you used the interpolated values to get the az1, dp1, az2, dp2 and d12 variables if I understood it well. If you adapt it to use only the original survey data of your table (length == 0) for the `locate` function, maybe it'll solve it. And interpolating azm and dip can be set to optional in case it takes much time.

> Regarding the performance, I think I know where exactly is the bottleneck. I will see if I can reduce the memory allocations and speedup the code in the process. I noticed that in the previous implementation you were computing various lengths for the intervals, maybe if you explain at a high-level what the algorithm was doing, I can try to reproduce it again. The current implementation does not compute lengths explicitly. I will check what is causing the slow down.

If it's the interpolation step, maybe it'll be solved after correcting the X, Y and Z. If it's the merge-tables step, we can check it later, I need to remember what I did earlier. But I really don't mind if it takes some seconds more and return the right results, my concern is only if it gets prohibitive at bigger datasets. You said you tried in a bigger one, so probably it's not an issue, although it'd be nice to try later in some other more complex (~1M intervals) just to confirm.

**Comment by juliohm** [comment]
After a long stretch preparing course material, I am finally back :)

>Yeah, maybe interpolating the azm and dip caused that. I used the original azm and dip from survey file and you used the interpolated values to get the az1, dp1, az2, dp2 and d12 variables if I understood it well. If you adapt it to use only the original survey data of your table (length == 0) for the locate function, maybe it'll solve it. And interpolating azm and dip can be set to optional in case it takes much time.

You mean that we should step forward using azm/dip values from the survey file first to compute the X, Y, Z at survey depths, and only then fill the X, Y and Z of the intervals from the interpolated azm/dip values? I wonder if that is what commercial softwares do? It seems to me that this method would introduce discontinuities at the survey depths.

In the current version of the PR I simply interpolate the azm/dip at interval depths using the azm/dip at survey depths, and then compute the X, Y, Z everywhere in a single shot with the step method (e.g. arc step) from the top to the bottom of the drillholes. This method guarantees a smooth trajectory, but as you pointed out the results differ from an important commercial software. I wonder if all major software follow the same standard? Is it documented somewhere?

>But I really don't mind if it takes some seconds more and return the right results, my concern is only if it gets prohibitive at bigger datasets. You said you tried in a bigger one, so probably it's not an issue, although it'd be nice to try later in some other more complex (~1M intervals) just to confirm.

Nice. I will try to test with the data set that you shared with me. I agree that we should first make sure that the result is correct. There is always room for performance optimizations after we get the expected results.

**Comment by juliohm** [comment]
@rmcaixeta can you double check the new implementation that I just pushed? Instead of interpolating AZM and DIP and then interpolating X, Y, Z, this new implementation interpolates X, Y, Z with the step function on the survey table and then interpolates the remaining X, Y, Z directly. If you can run your test script with the Leapfrog results that would be great.

**Comment by juliohm** [comment]
@rmcaixeta I've read the chapter of the book that talks about compositing. I am impressed by how under-specified these methods are. There are lots of details that are omitted and it is unlikely that anyone without access to commercial software can reproduce their results. I will read the current implementation in the master branch to see if I can write something that at least reproduces the results there.

**Comment by juliohm** [comment]
@rmcaixeta did you have a chance to compare the new desurvey with the leapfrog results?

**Comment by rmcaixeta** [comment]
Not yet, @juliohm . I'll probably have some time for it by mid August, I'll let you know

**Comment by juliohm** [comment]
@rmcaixeta quick question: what is the expected result of compositing an interval where some of the sub-intervals have missing values? For example, suppose the interval is made of 3 sub-intervals of length `0.1, 0.8, 0.1` with values `1.0, missing, 1.0`. Should the weighted average ignore the missing entry? `0.1*1.0 + 0.1*1.0 / (0.1 + 0.1)` ?

I am generalizing the code to work with scientific types from ScientificTypes.jl so that users can be explicit about the categorical nature of columns with strings or integer values for example.

**Comment by juliohm** [comment]
Or should these intervals be subdivided into smaller intervals guaranteed to not contain missing values? We really need a better reference to implement these methods...

**Comment by rmcaixeta** [comment]
Missing values are usually just ignored as a solution to not break the process as in your example. But sometimes softwares highlight that "there are missing values that may cause problems in the results" as it "cheats" during the sample regularization. Your second question of break intervals in missing values is not a standard because there might have missing values of a variable but not from others on that interval. But the intervals are usually broken when there is a gap in FROM-TO. In the actual version I made similar to Datamine where you can inform if every gap should be broken or if you consider gap intervals smaller than a given threshold as a "missing values"

**Comment by juliohm** [comment]
Awesome. I will just ignore the missings as suggested. I think the latest
commit in this PR already handles the gaps in FROM-TO.

Em ter., 27 de jul. de 2021 às 13:52, Rafael Caixeta <
***@***.***> escreveu:

**Comment by rmcaixeta** [comment]
Hey @juliohm . I took a quick look to try fixing the desurvey deviations. One thing I noticed is that you're interpolating azm and dip and not the vectors (if I understood your code correctly). This might be causing the differences. Check out the ang2vec and vec2ang transformations in the master version

**Comment by juliohm** [comment]
@rmcaixeta I can't find the functions you mentioned in the master branch. You mean we should interpolate azm and dip differently before running the step method? Also, notice that currently the code is using the step method in the survey rows, and the using simple interpolation for the remaining rows. Alternatively, one could apply the step method from top to bottom of the drillhole including rows from survey and interval tables (i.e. more steps of integration). Please let me know what is the preferred method.

**Comment by juliohm** [comment]
I will try to come back to this PR over the week or next week to finish the composite implementation and to update the README. After that, it will be just fine tuning to see what is causing differences with commercial software.

**Comment by rmcaixeta** [comment]
No hurry. Just to reference what I mentioned. Here, I first convert the azm and dip to unit vectors and then interpolate them (weighting according to the distance to the 2 [or 1] bounding surveys). While in your version it seems you're interpolating angles directly. The differences can also be something related to weighting these 1-2 closest surveys in the `interpolate!` function.
 
https://github.com/JuliaEarth/DrillHoles.jl/blob/d57fa990bb4f37696e521573ffb0651fa6cd5b17/src/desurvey.jl#L105-L124

**Comment by juliohm** [comment]
Thanks. We could also merge this PR after it is ready with the major updates to the API, and then you could submit a separate PR to fix the deviation calculation. It should be a very easy fix compared to the rest of the code that changed here.

I will try to finish the composite function and we see what is the best path to get things up-to-date and working as expected.

**Comment by rmcaixeta** [comment]
12m is still too much difference for me to merge. We'll merge once everything's running fine, no hurry

**Comment by juliohm** [comment]
Sure, just remember that merging into the master branch doesn't mean releasing a new version to end users, it just means that we would have a clean start to address the trajectory issue. Now that you are busy with your work and can't look into this closely I think a separate PR could help with documenting the trajectory fix to future potential contributors, but it is up to you.

**Comment by juliohm** [comment]
@rmcaixeta can you please clarify the functions `findbounds` and `weightedangs` in the master branch using a simple sketch?

**Comment by rmcaixeta** [comment]
image

**Comment by rmcaixeta** [comment]
image

**Comment by juliohm** [comment]
I will go ahead and merge this into master. That way people can use the new API and propose fixes to the functions in the master branch directly. After the master branch is functional I will go ahead and release a new version.

**Pull request merged**
